import { Userinfo } from "@/app/interface/Cardinterface";

export const PitGirls: any[] = [
    {
        name: "Elena Vasquez",
        url: "Elena Vasquez 001.jpg",
        age: 28,
        height: "1.72m",
        location: "Spain, Madrid",
        nationality: "Brazil",
        character: " Confident, Tactical, Resilient",
        hobbies: "Motorsport Influencer, Flamenco Dancing",
        job: "Fitness Instructor",
        education: "",
        highlight: "Celebrated for her ability to integrate her fitness expertise with a strategic approach to performance, using her knowledge to help clients excel both in the gym and in competitive racing.",
        description: "Elena Vasquez is a confident and tactical fitness instructor who brings a unique blend of technical expertise and passion for health to her role. Based in Madrid, Spain, Elena merges her strong background in sports science with her dedication to fitness, helping clients reach their peak performance. With a degree in Sports Science, Elena applies her in-depth knowledge of biomechanics and exercise physiology to craft personalized workout plans designed for optimal performance.Her tactical approach allows her to create effective training programs that cater to each client's specific needs and goals, ensuring continuous progress and efficiency.Outside the gym, Elena's interests in formula racing, motorsport analytics, and flamenco dancing reflect her dynamic personality and multifaceted skills. Her resilience and strategic mindset are not only evident in her professional work but also in her hobbies, where she combines analytical thinking with a flair for performance.Elena's expertise and unique perspective make her a standout fitness instructor, renowned for her ability to blend fitness training with a strategic approach to performance, helping clients excel in their fitness journeys and beyond."
    },
    {
        name: "Elena Vasquez",
        url: "Elena Vasquez 001.jpg",
        age: 28,
        height: "1.72m",
        location: "Spain, Madrid",
        nationality: "Brazil",
        character: " Confident, Tactical, Resilient",
        hobbies: "Motorsport Influencer, Flamenco Dancing",
        job: "Fitness Instructor",
        education: "",
        highlight: "Celebrated for her ability to integrate her fitness expertise with a strategic approach to performance, using her knowledge to help clients excel both in the gym and in competitive racing.",
        description: "Elena Vasquez is a confident and tactical fitness instructor who brings a unique blend of technical expertise and passion for health to her role. Based in Madrid, Spain, Elena merges her strong background in sports science with her dedication to fitness, helping clients reach their peak performance. With a degree in Sports Science, Elena applies her in-depth knowledge of biomechanics and exercise physiology to craft personalized workout plans designed for optimal performance.Her tactical approach allows her to create effective training programs that cater to each client's specific needs and goals, ensuring continuous progress and efficiency.Outside the gym, Elena's interests in formula racing, motorsport analytics, and flamenco dancing reflect her dynamic personality and multifaceted skills. Her resilience and strategic mindset are not only evident in her professional work but also in her hobbies, where she combines analytical thinking with a flair for performance.Elena's expertise and unique perspective make her a standout fitness instructor, renowned for her ability to blend fitness training with a strategic approach to performance, helping clients excel in their fitness journeys and beyond."
    },
    {
        name: "Elena Vasquez",
        url: "Elena Vasquez 001.jpg",
        age: 28,
        height: "1.72m",
        location: "Spain, Madrid",
        nationality: "Brazil",
        character: " Confident, Tactical, Resilient",
        hobbies: "Motorsport Influencer, Flamenco Dancing",
        job: "Fitness Instructor",
        education: "",
        highlight: "Celebrated for her ability to integrate her fitness expertise with a strategic approach to performance, using her knowledge to help clients excel both in the gym and in competitive racing.",
        description: "Elena Vasquez is a confident and tactical fitness instructor who brings a unique blend of technical expertise and passion for health to her role. Based in Madrid, Spain, Elena merges her strong background in sports science with her dedication to fitness, helping clients reach their peak performance. With a degree in Sports Science, Elena applies her in-depth knowledge of biomechanics and exercise physiology to craft personalized workout plans designed for optimal performance.Her tactical approach allows her to create effective training programs that cater to each client's specific needs and goals, ensuring continuous progress and efficiency.Outside the gym, Elena's interests in formula racing, motorsport analytics, and flamenco dancing reflect her dynamic personality and multifaceted skills. Her resilience and strategic mindset are not only evident in her professional work but also in her hobbies, where she combines analytical thinking with a flair for performance.Elena's expertise and unique perspective make her a standout fitness instructor, renowned for her ability to blend fitness training with a strategic approach to performance, helping clients excel in their fitness journeys and beyond."
    },
    {
        name: "Elena Vasquez",
        url: "Elena Vasquez 001.jpg",
        age: 28,
        height: "1.72m",
        location: "Spain, Madrid",
        nationality: "Brazil",
        character: " Confident, Tactical, Resilient",
        hobbies: "Motorsport Influencer, Flamenco Dancing",
        job: "Fitness Instructor",
        education: "",
        highlight: "Celebrated for her ability to integrate her fitness expertise with a strategic approach to performance, using her knowledge to help clients excel both in the gym and in competitive racing.",
        description: "Elena Vasquez is a confident and tactical fitness instructor who brings a unique blend of technical expertise and passion for health to her role. Based in Madrid, Spain, Elena merges her strong background in sports science with her dedication to fitness, helping clients reach their peak performance. With a degree in Sports Science, Elena applies her in-depth knowledge of biomechanics and exercise physiology to craft personalized workout plans designed for optimal performance.Her tactical approach allows her to create effective training programs that cater to each client's specific needs and goals, ensuring continuous progress and efficiency.Outside the gym, Elena's interests in formula racing, motorsport analytics, and flamenco dancing reflect her dynamic personality and multifaceted skills. Her resilience and strategic mindset are not only evident in her professional work but also in her hobbies, where she combines analytical thinking with a flair for performance.Elena's expertise and unique perspective make her a standout fitness instructor, renowned for her ability to blend fitness training with a strategic approach to performance, helping clients excel in their fitness journeys and beyond."
    },
    {
        name: "Elena Vasquez",
        url: "Elena Vasquez 001.jpg",
        age: 28,
        height: "1.72m",
        location: "Spain, Madrid",
        nationality: "Brazil",
        character: " Confident, Tactical, Resilient",
        hobbies: "Motorsport Influencer, Flamenco Dancing",
        job: "Fitness Instructor",
        education: "",
        highlight: "Celebrated for her ability to integrate her fitness expertise with a strategic approach to performance, using her knowledge to help clients excel both in the gym and in competitive racing.",
        description: "Elena Vasquez is a confident and tactical fitness instructor who brings a unique blend of technical expertise and passion for health to her role. Based in Madrid, Spain, Elena merges her strong background in sports science with her dedication to fitness, helping clients reach their peak performance. With a degree in Sports Science, Elena applies her in-depth knowledge of biomechanics and exercise physiology to craft personalized workout plans designed for optimal performance.Her tactical approach allows her to create effective training programs that cater to each client's specific needs and goals, ensuring continuous progress and efficiency.Outside the gym, Elena's interests in formula racing, motorsport analytics, and flamenco dancing reflect her dynamic personality and multifaceted skills. Her resilience and strategic mindset are not only evident in her professional work but also in her hobbies, where she combines analytical thinking with a flair for performance.Elena's expertise and unique perspective make her a standout fitness instructor, renowned for her ability to blend fitness training with a strategic approach to performance, helping clients excel in their fitness journeys and beyond."
    },
    {
        name: "Elena Vasquez",
        url: "Elena Vasquez 001.jpg",
        age: 28,
        height: "1.72m",
        location: "Spain, Madrid",
        nationality: "Brazil",
        character: " Confident, Tactical, Resilient",
        hobbies: "Motorsport Influencer, Flamenco Dancing",
        job: "Fitness Instructor",
        education: "",
        highlight: "Celebrated for her ability to integrate her fitness expertise with a strategic approach to performance, using her knowledge to help clients excel both in the gym and in competitive racing.",
        description: "Elena Vasquez is a confident and tactical fitness instructor who brings a unique blend of technical expertise and passion for health to her role. Based in Madrid, Spain, Elena merges her strong background in sports science with her dedication to fitness, helping clients reach their peak performance. With a degree in Sports Science, Elena applies her in-depth knowledge of biomechanics and exercise physiology to craft personalized workout plans designed for optimal performance.Her tactical approach allows her to create effective training programs that cater to each client's specific needs and goals, ensuring continuous progress and efficiency.Outside the gym, Elena's interests in formula racing, motorsport analytics, and flamenco dancing reflect her dynamic personality and multifaceted skills. Her resilience and strategic mindset are not only evident in her professional work but also in her hobbies, where she combines analytical thinking with a flair for performance.Elena's expertise and unique perspective make her a standout fitness instructor, renowned for her ability to blend fitness training with a strategic approach to performance, helping clients excel in their fitness journeys and beyond."
    },
    {
        name: "Elena Vasquez",
        url: "Elena Vasquez 001.jpg",
        age: 28,
        height: "1.72m",
        location: "Spain, Madrid",
        nationality: "Brazil",
        character: " Confident, Tactical, Resilient",
        hobbies: "Motorsport Influencer, Flamenco Dancing",
        job: "Fitness Instructor",
        education: "",
        highlight: "Celebrated for her ability to integrate her fitness expertise with a strategic approach to performance, using her knowledge to help clients excel both in the gym and in competitive racing.",
        description: "Elena Vasquez is a confident and tactical fitness instructor who brings a unique blend of technical expertise and passion for health to her role. Based in Madrid, Spain, Elena merges her strong background in sports science with her dedication to fitness, helping clients reach their peak performance. With a degree in Sports Science, Elena applies her in-depth knowledge of biomechanics and exercise physiology to craft personalized workout plans designed for optimal performance.Her tactical approach allows her to create effective training programs that cater to each client's specific needs and goals, ensuring continuous progress and efficiency.Outside the gym, Elena's interests in formula racing, motorsport analytics, and flamenco dancing reflect her dynamic personality and multifaceted skills. Her resilience and strategic mindset are not only evident in her professional work but also in her hobbies, where she combines analytical thinking with a flair for performance.Elena's expertise and unique perspective make her a standout fitness instructor, renowned for her ability to blend fitness training with a strategic approach to performance, helping clients excel in their fitness journeys and beyond."
    },
    {
        name: "Elena Vasquez",
        url: "Elena Vasquez 001.jpg",
        age: 28,
        height: "1.72m",
        location: "Spain, Madrid",
        nationality: "Brazil",
        character: " Confident, Tactical, Resilient",
        hobbies: "Motorsport Influencer, Flamenco Dancing",
        job: "Fitness Instructor",
        education: "",
        highlight: "Celebrated for her ability to integrate her fitness expertise with a strategic approach to performance, using her knowledge to help clients excel both in the gym and in competitive racing.",
        description: "Elena Vasquez is a confident and tactical fitness instructor who brings a unique blend of technical expertise and passion for health to her role. Based in Madrid, Spain, Elena merges her strong background in sports science with her dedication to fitness, helping clients reach their peak performance. With a degree in Sports Science, Elena applies her in-depth knowledge of biomechanics and exercise physiology to craft personalized workout plans designed for optimal performance.Her tactical approach allows her to create effective training programs that cater to each client's specific needs and goals, ensuring continuous progress and efficiency.Outside the gym, Elena's interests in formula racing, motorsport analytics, and flamenco dancing reflect her dynamic personality and multifaceted skills. Her resilience and strategic mindset are not only evident in her professional work but also in her hobbies, where she combines analytical thinking with a flair for performance.Elena's expertise and unique perspective make her a standout fitness instructor, renowned for her ability to blend fitness training with a strategic approach to performance, helping clients excel in their fitness journeys and beyond."
    },
    {
        name: "Elena Vasquez",
        url: "Elena Vasquez 001.jpg",
        age: 28,
        height: "1.72m",
        location: "Spain, Madrid",
        nationality : "Brazil",
        character: " Confident, Tactical, Resilient",
        hobbies: "Motorsport Influencer, Flamenco Dancing",
        job: "Fitness Instructor",
        education: "",
        highlight: "Celebrated for her ability to integrate her fitness expertise with a strategic approach to performance, using her knowledge to help clients excel both in the gym and in competitive racing.",
        description: "Elena Vasquez is a confident and tactical fitness instructor who brings a unique blend of technical expertise and passion for health to her role. Based in Madrid, Spain, Elena merges her strong background in sports science with her dedication to fitness, helping clients reach their peak performance. With a degree in Sports Science, Elena applies her in-depth knowledge of biomechanics and exercise physiology to craft personalized workout plans designed for optimal performance.Her tactical approach allows her to create effective training programs that cater to each client's specific needs and goals, ensuring continuous progress and efficiency.Outside the gym, Elena's interests in formula racing, motorsport analytics, and flamenco dancing reflect her dynamic personality and multifaceted skills. Her resilience and strategic mindset are not only evident in her professional work but also in her hobbies, where she combines analytical thinking with a flair for performance.Elena's expertise and unique perspective make her a standout fitness instructor, renowned for her ability to blend fitness training with a strategic approach to performance, helping clients excel in their fitness journeys and beyond."
    },
    {
        name: "Elena Vasquez",
        url: "Elena Vasquez 001.jpg",
        age: 28,
        height: "1.72m",
        location: "Spain, Madrid",
        nationality : "Brazil",
        character: " Confident, Tactical, Resilient",
        hobbies: "Motorsport Influencer, Flamenco Dancing",
        job: "Fitness Instructor",
        education: "",
        highlight: "Celebrated for her ability to integrate her fitness expertise with a strategic approach to performance, using her knowledge to help clients excel both in the gym and in competitive racing.",
        description: "Elena Vasquez is a confident and tactical fitness instructor who brings a unique blend of technical expertise and passion for health to her role. Based in Madrid, Spain, Elena merges her strong background in sports science with her dedication to fitness, helping clients reach their peak performance. With a degree in Sports Science, Elena applies her in-depth knowledge of biomechanics and exercise physiology to craft personalized workout plans designed for optimal performance.Her tactical approach allows her to create effective training programs that cater to each client's specific needs and goals, ensuring continuous progress and efficiency.Outside the gym, Elena's interests in formula racing, motorsport analytics, and flamenco dancing reflect her dynamic personality and multifaceted skills. Her resilience and strategic mindset are not only evident in her professional work but also in her hobbies, where she combines analytical thinking with a flair for performance.Elena's expertise and unique perspective make her a standout fitness instructor, renowned for her ability to blend fitness training with a strategic approach to performance, helping clients excel in their fitness journeys and beyond."
    },
]